import { fireEvent, render, screen, waitFor } from '@testing-library/react'
import { MemoryRouter } from 'react-router-dom'
import { beforeEach, expect, it, vi } from 'vitest'
import AdminFeedCatalogPage from '../src/pages/AdminFeedCatalogPage'
import FeedListPage from '../src/pages/FeedListPage'
const mocks = vi.hoisted(() => ({ listFeedCatalog: vi.fn(), listAdminFeedCatalog: vi.fn(), createCatalogItem: vi.fn(), updateCatalogItem: vi.fn(), checkCatalogItem: vi.fn(), publishCatalogItem: vi.fn() }))
const client = vi.hoisted(() => ({ getFeeds: vi.fn(), previewFeed: vi.fn(), addFeed: vi.fn() }))
vi.mock('../src/api/feedCatalog', () => mocks)
vi.mock('../src/api/client', async original => ({ ...await original<object>(), ...client }))
const item = { id: 1, title: '目录新闻', url: 'https://example.com/rss', category: '新闻', description: '每日新闻', sort_order: 1, published: false, revision: 2, check_status: 'unchecked', last_checked_at: null, last_error: '' }
beforeEach(() => { vi.resetAllMocks(); localStorage.clear(); mocks.listAdminFeedCatalog.mockResolvedValue([item]); mocks.listFeedCatalog.mockResolvedValue([item]); client.getFeeds.mockResolvedValue([]) })
it('ordinary readers cannot load admin data', () => {
  render(<AdminFeedCatalogPage user={{ is_admin: false }} />)
  expect(screen.getByText('仅管理员可访问公共推荐目录')).toBeTruthy()
  expect(mocks.listAdminFeedCatalog).not.toHaveBeenCalled()
})
it('checks then publishes and unpublishes using latest revisions', async () => {
  mocks.checkCatalogItem.mockResolvedValue({ ...item, revision: 3, check_status: 'ok' })
  mocks.publishCatalogItem.mockResolvedValueOnce({ ...item, revision: 4, published: true }).mockResolvedValueOnce({ ...item, revision: 5 })
  render(<AdminFeedCatalogPage user={{ is_admin: true }} />)
  fireEvent.click(await screen.findByRole('button', { name: '检查' }))
  await waitFor(() => expect(mocks.checkCatalogItem).toHaveBeenCalledWith(1, 2))
  await screen.findByText(/检查通过/)
  fireEvent.click(screen.getByRole('button', { name: '上架' }))
  await screen.findByRole('button', { name: '下架' })
  expect(mocks.publishCatalogItem).toHaveBeenCalledWith(1, true, 3)
  fireEvent.click(screen.getByRole('button', { name: '下架' }))
  await waitFor(() => expect(mocks.publishCatalogItem).toHaveBeenCalledWith(1, false, 4))
})
it('creates drafts and edits with revision, searches and filters', async () => {
  mocks.createCatalogItem.mockResolvedValue({ ...item, id: 2, title: '新增来源' })
  mocks.updateCatalogItem.mockResolvedValue({ ...item, title: '改名来源', revision: 3 })
  render(<AdminFeedCatalogPage user={{ is_admin: true }} />)
  await screen.findByText('目录新闻')
  fireEvent.click(screen.getByRole('button', { name: '新增条目' }))
  fireEvent.change(screen.getByLabelText('标题'), { target: { value: '新增来源' } })
  fireEvent.change(screen.getByLabelText('RSS 地址'), { target: { value: item.url } })
  fireEvent.change(screen.getByLabelText('分类'), { target: { value: '新闻' } })
  fireEvent.click(screen.getByRole('button', { name: '保存草稿' }))
  await screen.findByText('新增来源')
  expect(mocks.createCatalogItem.mock.calls[0][0].title).toBe('新增来源')
  fireEvent.change(screen.getByLabelText('搜索目录'), { target: { value: '目录新闻' } })
  fireEvent.click(screen.getByRole('button', { name: '编辑' }))
  fireEvent.change(screen.getByLabelText('标题'), { target: { value: '改名来源' } })
  fireEvent.click(screen.getByRole('button', { name: '保存修改' }))
  await waitFor(() => expect(mocks.updateCatalogItem).toHaveBeenCalledWith(1, expect.objectContaining({ title: '改名来源', revision: 2 })))
  fireEvent.change(screen.getByLabelText('搜索目录'), { target: { value: '' } })
  fireEvent.change(screen.getByLabelText('发布状态'), { target: { value: 'published' } })
  await screen.findByText('没有符合条件的条目')
})
it('loads public catalog and previews before subscribing', async () => {
  client.previewFeed.mockResolvedValue({ feed_title: '预览结果', actual_url: item.url, feed_type: 'rss', items: [] })
  render(<MemoryRouter><FeedListPage /></MemoryRouter>)
  fireEvent.click(await screen.findByRole('button', { name: item.title }))
  await screen.findByText('预览结果')
  expect(client.previewFeed).toHaveBeenCalledWith(item.url, expect.any(AbortSignal))
  expect(client.addFeed).not.toHaveBeenCalled()
})
it('public catalog failure has retry and never a hardcoded fallback', async () => {
  mocks.listFeedCatalog.mockRejectedValueOnce(new Error('offline')).mockResolvedValueOnce([])
  render(<MemoryRouter><FeedListPage /></MemoryRouter>)
  await screen.findByText('推荐目录加载失败')
  expect(screen.queryByText('影视飓风')).toBeNull()
  fireEvent.click(screen.getByRole('button', { name: '重试加载推荐' }))
  await screen.findByText('暂无已上架的推荐')
})
it('keeps failed validation as a draft and allows retry', async () => {
  mocks.checkCatalogItem.mockResolvedValue({ ...item, revision: 3, check_status: 'failed', last_error: '源不可解析', last_checked_at: '2026-09-17T00:00:00Z' })
  render(<AdminFeedCatalogPage user={{ is_admin: true }} />)
  fireEvent.click(await screen.findByRole('button', { name: '检查' }))
  await screen.findByText('源不可解析')
  expect(screen.getByText('草稿', { selector: 'span' })).toBeTruthy()
  fireEvent.click(screen.getByRole('button', { name: '检查' }))
  await waitFor(() => expect(mocks.checkCatalogItem).toHaveBeenLastCalledWith(1, 3))
})
it('disables repeated mutations and recovers after conflicts by refreshing', async () => {
  let reject!: (reason: unknown) => void
  mocks.publishCatalogItem.mockImplementation(() => new Promise((_resolve, failure) => { reject = failure }))
  render(<AdminFeedCatalogPage user={{ is_admin: true }} />)
  fireEvent.click(await screen.findByRole('button', { name: '上架' }))
  fireEvent.click(screen.getByRole('button', { name: '上架' }))
  expect(mocks.publishCatalogItem).toHaveBeenCalledTimes(1)
  reject({ response: { status: 409 } })
  await screen.findByText('条目已被修改，请刷新列表后重新编辑或操作。')
  mocks.listAdminFeedCatalog.mockResolvedValue([{ ...item, revision: 9 }])
  fireEvent.click(screen.getByRole('button', { name: '刷新列表' }))
  await waitFor(() => expect(mocks.listAdminFeedCatalog).toHaveBeenCalledTimes(2))
  mocks.checkCatalogItem.mockResolvedValue({ ...item, revision: 10, check_status: 'ok' })
  fireEvent.click(screen.getByRole('button', { name: '检查' }))
  await waitFor(() => expect(mocks.checkCatalogItem).toHaveBeenCalledWith(1, 9))
})
it('refreshes recorded check failure after rejected publication so retry uses current revision', async () => {
  mocks.publishCatalogItem.mockRejectedValue({ response: { status: 422, data: { error: '上架检查失败' } } })
  render(<AdminFeedCatalogPage user={{ is_admin: true }} />)
  await screen.findByText('目录新闻')
  mocks.listAdminFeedCatalog.mockResolvedValue([{ ...item, revision: 3, check_status: 'failed', last_error: 'RSS 无效' }])
  fireEvent.click(screen.getByRole('button', { name: '上架' }))
  await screen.findByText('RSS 无效')
  expect(screen.getByRole('alert').textContent).toBe('上架检查失败')
  fireEvent.click(screen.getByRole('button', { name: '上架' }))
  await waitFor(() => expect(mocks.publishCatalogItem).toHaveBeenLastCalledWith(1, true, 3))
})
