import { act, fireEvent, render, screen } from '@testing-library/react'
import { afterEach, describe, expect, it, vi } from 'vitest'
import { ReaderActionContext } from '../src/reader/ReaderActionContext'
import { ReaderInteractionSurface } from '../src/reader/ReaderInteractionSurface'
import type { ReaderActionContextValue } from '../src/reader/types'

function context(overrides: Partial<ReaderActionContextValue> = {}): ReaderActionContextValue {
  return {
    normalizeLink: (href) => {
      try {
        const url = new URL(href, 'https://reader.example/article')
        return /^https?:$/.test(url.protocol) ? url.href : null
      } catch {
        return null
      }
    },
    getLinkState: () => null,
    getActions: () => [{ id: 'add', label: '加入待抓取', run: vi.fn() }],
    ...overrides,
  }
}

function subject(markup = (
  <p>
    <span>Before </span><a href="/a">Alpha readable link</a>
    <span> middle </span><a href="/b">Beta link</a><span> after</span>
  </p>
), value = context()) {
  return render(
    <ReaderActionContext.Provider value={value}>
      <ReaderInteractionSurface articleKey="article-1">{markup}</ReaderInteractionSurface>
    </ReaderActionContext.Provider>,
  )
}

function select(start: Node, startOffset: number, end: Node, endOffset: number) {
  const range = document.createRange()
  range.setStart(start, startOffset)
  range.setEnd(end, endOffset)
  const selection = window.getSelection()!
  selection.removeAllRanges()
  selection.addRange(range)
}

afterEach(() => {
  vi.useRealTimers()
  window.getSelection()?.removeAllRanges()
})

describe('ReaderInteractionSurface desktop selection', () => {
  it('opens after pointerup and highlights the complete partially-selected link', () => {
    subject()
    const anchor = screen.getByRole('link', { name: 'Alpha readable link' })
    select(anchor.firstChild!, 6, anchor.firstChild!, 14)

    fireEvent.pointerUp(anchor, { pointerType: 'mouse' })

    expect(screen.getByRole('menu')).toBeTruthy()
    expect(anchor.classList.contains('reader-context-target')).toBe(true)
  })

  it('opens after a keyboard Selection stabilizes', () => {
    subject()
    const anchor = screen.getByRole('link', { name: 'Alpha readable link' })
    select(anchor.firstChild!, 2, anchor.firstChild!, 8)
    fireEvent.keyUp(anchor, { key: 'Shift' })
    expect(screen.getByRole('menu')).toBeTruthy()
    expect(anchor.classList.contains('reader-context-target')).toBe(true)
  })

  it('replaces a non-collapsed Selection on selectionchange but keeps a snapshot when menu focus collapses it', () => {
    subject()
    const [first, second] = screen.getAllByRole('link')
    select(first.firstChild!, 1, first.firstChild!, 4)
    fireEvent.pointerUp(first, { pointerType: 'mouse' })

    select(second.firstChild!, 1, second.firstChild!, 4)
    fireEvent(document, new Event('selectionchange'))
    expect(first.classList.contains('reader-context-target')).toBe(false)
    expect(second.classList.contains('reader-context-target')).toBe(true)

    window.getSelection()!.removeAllRanges()
    fireEvent(document, new Event('selectionchange'))
    expect(screen.getByRole('menu')).toBeTruthy()
    expect(second.classList.contains('reader-context-target')).toBe(true)
  })

  it('stays closed for pure text and highlights every selected link', () => {
    subject()
    const spans = document.querySelectorAll('span')
    select(spans[0].firstChild!, 0, spans[0].firstChild!, 3)
    fireEvent.pointerUp(spans[0], { pointerType: 'mouse' })
    expect(screen.queryByRole('menu')).toBeNull()

    select(spans[0].firstChild!, 1, spans[2].firstChild!, 2)
    fireEvent.pointerUp(spans[2], { pointerType: 'mouse' })
    expect(screen.getByRole('menu')).toBeTruthy()
    expect(document.querySelectorAll('a.reader-context-target')).toHaveLength(2)
  })

  it('never prevents the ordinary mouse context menu', () => {
    subject()
    const anchor = screen.getByRole('link', { name: 'Alpha readable link' })
    expect(fireEvent.contextMenu(anchor, { pointerType: 'mouse' })).toBe(true)
  })

  it('suppresses only the click generated by drag selection', () => {
    const clicked = vi.fn()
    subject(<p><a href="#ok" onClick={clicked}>Alpha readable link</a></p>)
    const anchor = screen.getByRole('link')
    select(anchor.firstChild!, 1, anchor.firstChild!, 5)
    fireEvent.pointerUp(anchor, { pointerType: 'mouse' })

    expect(fireEvent.click(anchor)).toBe(false)
    expect(clicked).not.toHaveBeenCalled()
    expect(fireEvent.click(anchor)).toBe(true)
    expect(clicked).toHaveBeenCalledTimes(1)
  })

  it('does not suppress an unrelated link click and clears suppression when closed', () => {
    const firstClick = vi.fn((event: React.MouseEvent) => event.preventDefault())
    const secondClick = vi.fn((event: React.MouseEvent) => event.preventDefault())
    subject(<p><a href="/a" onClick={firstClick}>First link</a> <a href="/b" onClick={secondClick}>Second link</a></p>)
    const [first, second] = screen.getAllByRole('link')
    select(first.firstChild!, 1, first.firstChild!, 4)
    fireEvent.pointerUp(first, { pointerType: 'mouse' })
    fireEvent.click(second)
    expect(secondClick).toHaveBeenCalledTimes(1)

    fireEvent.keyDown(screen.getByRole('menuitem'), { key: 'Escape' })
    fireEvent.click(first)
    expect(firstClick).toHaveBeenCalledTimes(1)
  })

  it('allows an ordinary link click when there was no selection', () => {
    const clicked = vi.fn((event: React.MouseEvent) => event.preventDefault())
    subject(<p><a href="/a" onClick={clicked}>Alpha readable link</a></p>)
    fireEvent.click(screen.getByRole('link'))
    expect(clicked).toHaveBeenCalledTimes(1)
  })

  it('closes and removes highlights on Escape or scroll', () => {
    subject()
    const anchor = screen.getByRole('link', { name: 'Alpha readable link' })
    select(anchor.firstChild!, 0, anchor.firstChild!, 3)
    fireEvent.pointerUp(anchor, { pointerType: 'mouse' })
    fireEvent.keyDown(screen.getByRole('menuitem'), { key: 'Escape' })
    expect(screen.queryByRole('menu')).toBeNull()
    expect(anchor.classList.contains('reader-context-target')).toBe(false)
    expect(document.activeElement).toBe(anchor)

    select(anchor.firstChild!, 0, anchor.firstChild!, 3)
    fireEvent.pointerUp(anchor, { pointerType: 'mouse' })
    fireEvent.scroll(window)
    expect(screen.queryByRole('menu')).toBeNull()
    expect(anchor.classList.contains('reader-context-target')).toBe(false)
  })

  it('replaces a target snapshot and cleans classes on unmount', () => {
    const { unmount } = subject()
    const [first, second] = screen.getAllByRole('link')
    select(first.firstChild!, 0, first.firstChild!, 2)
    fireEvent.pointerUp(first, { pointerType: 'mouse' })
    select(second.firstChild!, 0, second.firstChild!, 2)
    fireEvent.pointerUp(second, { pointerType: 'mouse' })
    expect(first.classList.contains('reader-context-target')).toBe(false)
    expect(second.classList.contains('reader-context-target')).toBe(true)
    unmount()
    expect(second.classList.contains('reader-context-target')).toBe(false)
  })
})

describe('ReaderInteractionSurface touch long press', () => {
  it('opens at 500ms, then suppresses the generated click and touch contextmenu only', () => {
    vi.useFakeTimers()
    subject()
    const anchor = screen.getByRole('link', { name: 'Alpha readable link' })
    fireEvent.pointerDown(anchor, { pointerType: 'touch', pointerId: 1, clientX: 10, clientY: 20 })
    act(() => vi.advanceTimersByTime(499))
    expect(screen.queryByRole('menu')).toBeNull()
    act(() => vi.advanceTimersByTime(1))
    expect(screen.getByRole('menu')).toBeTruthy()
    expect(anchor.classList.contains('reader-context-target')).toBe(true)
    expect(fireEvent.click(anchor)).toBe(false)
    expect(fireEvent.contextMenu(anchor, { pointerType: 'touch' })).toBe(false)
    expect(fireEvent.contextMenu(anchor, { pointerType: 'mouse' })).toBe(true)
  })

  it('does not suppress click or touch contextmenu on another link', () => {
    vi.useFakeTimers()
    const secondClick = vi.fn((event: React.MouseEvent) => event.preventDefault())
    subject(<p><a href="/a">First link</a> <a href="/b" onClick={secondClick}>Second link</a></p>)
    const [first, second] = screen.getAllByRole('link')
    fireEvent.pointerDown(first, { pointerType: 'touch', pointerId: 1, clientX: 10, clientY: 20 })
    act(() => vi.advanceTimersByTime(500))
    expect(screen.getByRole('menu')).toBeTruthy()
    expect(fireEvent.click(second)).toBe(false)
    expect(secondClick).toHaveBeenCalledTimes(1)
    expect(fireEvent.contextMenu(second, { pointerType: 'touch' })).toBe(true)
    expect(fireEvent.contextMenu(first, { pointerType: 'touch' })).toBe(false)
  })

  it.each([
    ['movement', (anchor: HTMLElement) => fireEvent.pointerMove(anchor, { pointerType: 'touch', pointerId: 1, clientX: 19, clientY: 20 })],
    ['pointer cancellation', (anchor: HTMLElement) => fireEvent.pointerCancel(anchor, { pointerType: 'touch', pointerId: 1 })],
    ['early release', (anchor: HTMLElement) => fireEvent.pointerUp(anchor, { pointerType: 'touch', pointerId: 1 })],
    ['scroll', () => fireEvent.scroll(window)],
  ])('cancels on %s', (_name, cancel) => {
    vi.useFakeTimers()
    subject()
    const anchor = screen.getByRole('link', { name: 'Alpha readable link' })
    fireEvent.pointerDown(anchor, { pointerType: 'touch', pointerId: 1, clientX: 10, clientY: 20 })
    cancel(anchor)
    act(() => vi.advanceTimersByTime(500))
    expect(screen.queryByRole('menu')).toBeNull()
  })

  it('cancels when the touch is released outside the reader surface', () => {
    vi.useFakeTimers()
    subject()
    const anchor = screen.getByRole('link', { name: 'Alpha readable link' })
    fireEvent.pointerDown(anchor, { pointerType: 'touch', pointerId: 1, clientX: 10, clientY: 20 })
    fireEvent.pointerUp(window, { pointerType: 'touch', pointerId: 1 })
    act(() => vi.advanceTimersByTime(500))
    expect(screen.queryByRole('menu')).toBeNull()
  })
})
